export const states = [
	{ sigla: 'AC', name: 'Acre' },
	{ sigla: 'AL', name: 'Alagoas' },
	{ sigla: 'AP', name: 'Amapá' },
	{ sigla: 'AM', name: 'Amazonas' },
	{ sigla: 'BA', name: 'Bahia' },
	{ sigla: 'CE', name: 'Ceará' },
	{ sigla: 'DF', name: 'Distrito Federal' },
	{ sigla: 'ES', name: 'Espírito Santo' },
	{ sigla: 'GO', name: 'Goiás' },
	{ sigla: 'MA', name: 'Maranhão' },
	{ sigla: 'MT', name: 'Mato Grosso' },
	{ sigla: 'MS', name: 'Mato Grosso do Sul' },
	{ sigla: 'MG', name: 'Minas Gerais' },
	{ sigla: 'PA', name: 'Pará' },
	{ sigla: 'PB', name: 'Paraíba' },
	{ sigla: 'PR', name: 'Paraná' },
	{ sigla: 'PE', name: 'Pernambuco' },
	{ sigla: 'PI', name: 'Piauí' },
	{ sigla: 'RJ', name: 'Rio de Janeiro' },
	{ sigla: 'RN', name: 'Rio Grande do Norte' },
	{ sigla: 'RS', name: 'Rio Grande do Sul' },
	{ sigla: 'RO', name: 'Rondônia' },
	{ sigla: 'RR', name: 'Roraima' },
	{ sigla: 'SC', name: 'Santa Catarina' },
	{ sigla: 'SP', name: 'São Paulo' },
	{ sigla: 'SE', name: 'Sergipe' },
	{ sigla: 'TO', name: 'Tocantins' },
];
