version: '3.3'

services:
  lab77-database-mysql:
    container_name: lab77-database-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dev-lab77'
      MYSQL_ROOT_PASSWORD: 'lab77'
    ports:
      - '3316:3306'
    expose:
      - '3306'
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d

  lab77-database-mongo:
    container_name: lab77-database-mongo
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root-lab77'
      MONGO_INITDB_ROOT_PASSWORD: 'root-lab77'
      MONGO_INITDB_DATABASE: 'dev-lab77'
    ports:
      - '27030:27017'
    expose:
      - '27017'
    volumes:
      - ./.docker/mongodb:/docker-entrypoint-initdb.d
      - ./.docker/mongodb/seed:/seed
