name: Packages

on:
  push:
    tags:
      - v* # Somente publica quando tiver uma nova tag

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lab77store'
      # Install
      - name: Install Packages
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Publish
      - name: Publish database
        run: cd projects/database && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish domains
        run: cd projects/domains && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
